---
root: true

plugins:
  - prettier

env:
  node: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:prettier/recommended'

rules:
  no-console: 0
  import/extensions: 0
  prettier/prettier: error
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]